---
ava_user: avalanche
ava_group: admin
ava_uid: 1014
network: mainnet
db_dir: /data/cryftgo
log_dir: /var/log/cryftgo
config_dir: /etc/cryftgo
repo_url: https://github.com/cryft-labs/cryftgo
repo_folder: /tmp/cryftgo
